### PR TITLE
Enable all prefixes for named parameters and allow for unused named parameters

### PR DESCRIPTION
**Pull request by gber**
Particularly "@"-based named parameters should be supported since they are mentioned in the Go documentation. This fixes issues #499 and #697.

### CODE REVIEW

**Comment by mattn** [comment]
Please add tests.

**Comment by gber** [comment]
OK, added in commit ccbad97.

**Comment by mattn** [comment]
Thank you. Will merge after CI passed.

**Comment by gber** [comment]
Can you merge this? CI has passed for go >= 1.13 and the failures for earlier versions seem unrelated due to a dependency.

**Comment by mattn** [comment]
Thank you

**Pull request merged**
