### PR TITLE
bump sqlite3 3.24.0 and add TestUpsert.

### PR DESCRIPTION
**Pull request by tuxlinuxien**
Upsert has been added to SQLite3 v3.24.0.

Since this feature has been wanted for quite a longtime, I hope we can see it soon and prod ready for go-sqlite3.

Best regards.

### CODE REVIEW

**Comment by GJRTimmer** [comment]
Quick question: Did you do an manual update or did you used the provided upgrade tool?

**Comment by tuxlinuxien** [comment]
Did it manually. But I will do it with the upgrade tool.

**Comment by tuxlinuxien** [comment]
@GJRTimmer I see my error when I don't use the upgrade tool, it had messed up with the includes. my latest commit fix that. 

Thank for your tip.

**Comment by GJRTimmer** [comment]
@tuxlinuxien The new upgrade tool merges the User Authentication Module into the main binding, currently requried because this has been included within the master.

**Comment by tuxlinuxien** [comment]
@GJRTimmer I have closed this PR and created a new one ( #589 ). I have used the upgrade tool and fixed the TestUpsert.

**Pull request closed without merging**
