### PR TITLE
Unit test showing "database disk image is malformed" issue

### PR DESCRIPTION
**Pull request by otoolep**

### CODE REVIEW

**Comment by otoolep** [comment]
I'm dealing with an issue in rqlite (see https://github.com/rqlite/rqlite/issues/1103) which I've managed to reproduce with a simple unit test for this library. When I run the test shown in this PR I get the following output (ran it twice, happens within seconds):

```bash
$ go test -run Test_TableCreationInMemoryLoadRaw
--- FAIL: Test_TableCreationInMemoryLoadRaw (2.30s)
    malformed_test.go:59: rows had error after Next() (1203 loops): database disk image is malformed
FAIL
exit status 1
FAIL	github.com/mattn/go-sqlite3	2.303s
$ go test -run Test_TableCreationInMemoryLoadRaw
--- FAIL: Test_TableCreationInMemoryLoadRaw (2.74s)
    malformed_test.go:59: rows had error after Next() (1346 loops): database disk image is malformed
FAIL
exit status 1
FAIL	github.com/mattn/go-sqlite3	2.744s
```

Any idea what is going wrong? Am I using the library incorrectly?

**Comment by rittneje** [comment]
I don't know what the underlying issue is, but I was able to get a bit more information from the SQLite error logs.
> 11: database corruption at line 69145 of [a29f994989]
11: statement aborts at 2: [SELECT COUNT(*) FROM logs] database disk image is malformed

That means the corruption is detected on line 69145 of [sqlite3-binding.c](https://raw.githubusercontent.com/mattn/go-sqlite3/master/sqlite3-binding.c). However, this output is not consistent - sometimes the corruption is detected on line 70169, but usually it is on line 69145.

That is deeper in the internals of the library than I am familiar with. If you can reproduce with a pure C version (using pthreads I guess) then you should file a bug on [the forum](https://sqlite.org/forum/forummain).

**Comment by otoolep** [comment]
Thanks very much @rittneje -- yeah, reproducing using just the SQLite library would be the next step. I'll see if I can do that.

I already created a message on the SQLite forum: https://sqlite.org/forum/forumpost/701d907e99

**Comment by otoolep** [comment]
Closing now, since this was just a demonstration.

**Comment by rittneje** [comment]
@otoolep BTW, I am using Linux Ubuntu 20.04.5.

**Comment by otoolep** [comment]
Me too. This has also been reported on Alpine Linux v3.16.

**Comment by otoolep** [comment]
This is my box:
```bash
~ $ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
~ $ uname -a
Linux marx 5.15.0-52-generic #58~20.04.1-Ubuntu SMP Thu Oct 13 13:09:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by otoolep** [comment]
@rittneje  -- any input on this question? https://sqlite.org/forum/forumpost/7db6cc01d3e65add

**Comment by otoolep** [comment]
@rittneje -- curious if you have any opinion on the following. I wrote a C version of this Go code shown in this PR. You can see it at https://github.com/otoolep/sqlite-c-test/blob/main/in-memory.c

```bash
~/repos/sqlite-c-test (main)$ gcc in-memory.c -pthread -l sqlite3
~/repos/sqlite-c-test (main)$ ./a.out 
Failed to fetch data: database is locked
~/repos/sqlite-c-test (main)$ 
```
which is not entirely surprising. However I was wondering *why* I don't get the same result from this repo -- I get "database corrupted", not LOCKED. Is mattn/go-sqlite3 doing something special to backoff during reads if the database is locked? Does it register a BUSY handler, or something?

**Comment by otoolep** [comment]
I have just updated [my code](https://github.com/otoolep/sqlite-c-test/blob/main/in-memory.c) -- added a busy timeout (which fixed the LOCKED issue) and querying in a loop. Everything seems to work fine.
```bash
~/repos/sqlite-c-test (main)$ gcc in-memory.c -pthread -l sqlite3
~/repos/sqlite-c-test (main)$ time ./a.out 
Count during loop is: 9
Count during loop is: 435969
Count during loop is: 859941
Count during loop is: 1298586
Count during loop is: 2170735
Fetched 10000000 times without error
Count is: 10000000

real	0m51.566s
user	1m13.881s
sys	0m0.128s
~/repos/sqlite-c-test (main)$ 
```
Any idea? Looks like this issue is not reproducible via C.

**Comment by rittneje** [comment]
You forgot to call `sqlite3_step` on the prepared statement for `SELECT * FROM logs`.

**Comment by otoolep** [comment]
@rittneje -- thanks. I fixed up the C code (note that I changed the query to `COUNT` like the Go unit test )and can now reproduce the issue!

```bash
~/repos/sqlite-c-test (main)$ gcc in-memory.c -pthread -l sqlite3
~/repos/sqlite-c-test (main)$ ./a.out 
Failed to step data: database disk image is malformed
```

Before I post a new issue on the SQLite forum, would you take one last look at the C code? Just in case anything stupid is there?

https://github.com/otoolep/sqlite-c-test/blob/main/in-memory.c

**Comment by rittneje** [comment]
Your C code seems fine. I am able to observe the same failure with the latest amalgamation (3.40.0).

**Comment by otoolep** [comment]
I fixed up the C code. https://github.com/otoolep/sqlite-c-test/commit/a192ff9368e99b18e36741af7cf0c6957a835c4d

Still fails.

**Comment by otoolep** [comment]
https://sqlite.org/forum/forumpost/d443fb0730 just posted.

**Comment by otoolep** [comment]
Root cause is a bug in SQLite!

Confirmation: https://sqlite.org/forum/forumpost/705955d7110e89a5

Fix: https://www.sqlite.org/src/info/d18cce37b5b73bb2

**Pull request closed without merging**
