### PR TITLE
added missing mode functionality

### PR DESCRIPTION
**Pull request by AshfordN**
the mode option in the dsn did not work as expected, particularly when trying to open a database in read-only mode

### CODE REVIEW

**Comment by rittneje** [comment]
@AshfordN Do you have an example of it not working correctly? The mode parameter is handled by SQLite itself and is basically applied on top of `SQLITE_OPEN_READWRITE`/`SQLITE_OPEN_READONLY`/`SQLITE_OPEN_CREATE`. Therefore, this change is not needed.

**Comment by AshfordN** [comment]
Well the database isn't actually read-only when you specify mode=ro

**Comment by rittneje** [comment]
Please provide an example code segment where it does not work as expected.

**Comment by AshfordN** [comment]
The following code successfully inserts and updates a record in the database, using go1.13.1 on linux/amd64:

```
package main

import (
	"database/sql"
	"fmt"

	_ "github.com/mattn/go-sqlite3"
)

func main() {
	//open database
	db, err := sql.Open("sqlite3", "main.db?mode=ro")
	if err != nil {
		panic(err)
	}

	//attempt insert
	if _, err := db.Exec("INSERT INTO test(col1, col2) VALUES(1, 2)"); err != nil {
		fmt.Printf("Insert failed: %w\n", err)
	}

	//attempt update
	if _, err := db.Exec("UPDATE test SET col2 = 4 WHERE col1 = 1"); err != nil {
		fmt.Printf("Update failed: %w\n", err)
	}
}
```

**Comment by rittneje** [comment]
See https://www.sqlite.org/uri.html. It should be `sql.Open("sqlite3", "file:main.db?mode=ro")`.

**Comment by AshfordN** [comment]
Ok, this works, thanks.

**Pull request closed without merging**
