### PR TITLE
actually link to <sqlite3.h> when -tags libsqlite3

### LINKED ISSUE #330: go-sqlite3 still using built-in copy despite libsqlite3 tag
Building with -tags libsqlite3, while it does seem to be using the sqlite3.h from the system, still appears to be using the built-in copy of the actual code rather than linking against the system library.
```
stgraber@castiana:~/data/code/go/src/github.com/mattn/go-sqlite3 (master)$ go build -tags libsqlite3 _example/simple/simple.go
stgraber@castiana:~/data/code/go/src/github.com/mattn/go-sqlite3 (master)$ ldd simple | grep sqlite
```

Now if I actually remove the embedded copy and try again (no other changes):
```
stgraber@castiana:~/data/code/go/src/github.com/mattn/go-sqlite3 (master)$ rm sqlite3-binding.*
stgraber@castiana:~/data/code/go/src/github.com/mattn/go-sqlite3 (master)$ go build -tags libsqlite3 _example/simple/simple.go
stgraber@castiana:~/data/code/go/src/github.com/mattn/go-sqlite3 (master)$ ldd simple | grep sqlite
        libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007f8ba57ea000)
```

Any idea what's going on?

### PR DESCRIPTION
**Pull request by brauner**
Building with -tags libsqlite3 used the sqlite3.h from the system but the go
compiler will compile all *.{c,h} files in the same direcory:

	"When the Go tool sees that one or more Go files use the special import
	"C", it will look for other non-Go files in the directory and compile
	them as part of the Go package. Any .c, .s, or .S files will be compiled
	with the C compiler." (https://golang.org/cmd/cgo/)

So if users actually want to link against the system sqlite3 we should make
sqlite3-binding.* a noop.

Signed-off-by: Christian Brauner <christian.brauner@canonical.com>

Closes #330.

After the patch:

1. linking against system `sqlite3`:
```
chb@conventiont|~/source/go/src/github.com/mattn/go-sqlite3|2016-10-17/fix_libsqlite3_build>
> go build -tags libsqlite3 _example/simple/simple.go
chb@conventiont|~/source/go/src/github.com/mattn/go-sqlite3|2016-10-17/fix_libsqlite3_build %>
> ldd simple | grep sqlite
        libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007f860d0a4000)
```

2. using vendored `sqlite3`:
```
chb@conventiont|~/source/go/src/github.com/mattn/go-sqlite3|2016-10-17/fix_libsqlite3_build %>
> go build _example/simple/simple.go
chb@conventiont|~/source/go/src/github.com/mattn/go-sqlite3|2016-10-17/fix_libsqlite3_build %>
> ldd simple | grep sqlite
```

### CODE REVIEW

**Comment by brauner** [comment]
@mattn ping. We'd really like to see this issue resolved. Would be great if you could take a look whether this pr is enough. :)

**Comment by mattn** [comment]
please update tool/upgrade.go too

**Comment by brauner** [comment]
@mattn, done.

**Comment by mattn** [comment]
LGTM!

**Comment by mattn** [comment]
Thanks!

**Comment by marienz** [comment]
See also #318. This was previously handled using a `+build !libsqlite3` build tag. The `go` tool recognizes such tags even in non-Go source, and does not invoke the C compiler at all. I'd argue that's a tidier solution than this one, which runs the C compiler on an effectively empty file.

**Pull request merged**
