### PR TITLE
Adds a fuzz target

### PR DESCRIPTION
**Pull request by catenacyber**
Cf https://github.com/google/oss-fuzz/pull/4946

This will allow oss-fuzz integration, and thus continuous fuzzing.

@mattn does this fuzz target look good to you ?

### CODE REVIEW

**Comment by catenacyber** [comment]
If we only call `C.sqlite3_close_v2(db)` and not `conn.Close()`, we do not call `deleteHandles` which frees some memory with `C.free(handle)`

I guess other lines have to be fixed this way

**Comment by catenacyber** [comment]
Friendly ping on this PR @mattn  ?

**Comment by mattn** [comment]
Thank you

**Comment by mattn** [comment]
Hmm, go-acc refer older version of hashicorp/hcl. So CI got fails. @catenacyber Can you handle this issue?

**Comment by catenacyber** [comment]
I do not see the CI failure for this PR (which also does not mention neither go-acc nor hashicorp)...
So, I am not sure what you mean... Could you provide me some pointers ?

**Comment by mattn** [comment]
All tests are failing https://github.com/mattn/go-sqlite3/runs/1903852468

**Comment by catenacyber** [comment]
I created https://github.com/mattn/go-sqlite3/pull/915

**Pull request merged**
