### PR TITLE
enable common cflags for perf

### PR DESCRIPTION
**Pull request by jmoiron**
* enable [HAVE_USLEEP](http://beets.io/blog/sqlite-nightmare.html)
* enable intrinsics

### CODE REVIEW

**Comment by jmoiron** [comment]
there are other open PRs for this, presumably you don't want the intrinsics thing here, but HAVE_USLEEP is a common issue

**Comment by mattn** [comment]
Seems removing SQLITE_DISABLE_INTRINSIC, It fixes this too?

https://github.com/mattn/go-sqlite3/issues/386

**Comment by jmoiron** [comment]
@mattn I removed it only for perf reason but if it fixes something too that's good!  The USLEEP thing is very difficult to find, tests randomly/suspiciously take 1.001s

**Comment by mattn** [comment]
@otoolep could you please check this abount #386 ?

**Comment by jmoiron** [comment]
Chasing this down some more, I've written a [benchmark](https://raw.githubusercontent.com/DataDog/go-sqlite3/5665348fc135ca1addbb607f4c5b3f4ba1df8e93/_example/multi/multi_test.go) that shows that even with `-DHAVE_USLEEP` multi-threaded inserts to _different_ sqlite dbs can still have some kind of weird contention issues.  

```
$GOPATH/src/github.com/DataDog/go-sqlite3/_example/multi (jason/multi-test *)$ go test -bench . -v
BenchmarkMultiWrite-4   	      50	 131837868 ns/op
--- BENCH: BenchmarkMultiWrite-4
	multi_test.go:108: total rows: 3
	multi_test.go:108: total rows: 6
	multi_test.go:108: total rows: 9
	multi_test.go:80: slow bench, top 3 (median: 33.655557ms, avg: 131.837148ms):
	multi_test.go:82:  1.299541798s
	multi_test.go:82:  673.901154ms
	multi_test.go:82:  664.089833ms
	multi_test.go:108: total rows: 150
PASS
ok  	github.com/DataDog/go-sqlite3/_example/multi	8.391s
```

via https://github.com/DataDog/go-sqlite3/pull/2

**Comment by GJRTimmer** [comment]
`usleep` implemented; closed

**Pull request closed without merging**
