### PR TITLE
fix/306

### PR DESCRIPTION
**Pull request by GJRTimmer**
Add: -lpthread for PowerPC

* ppc
* ppc64
* ppc64le

Fixes: #306

### CODE REVIEW

**Comment by GJRTimmer** [comment]
@tdolby await Travis-CI and you final test of latest pull of `fix/306`

**Comment by mattn** [comment]
LGTM

**Comment by tdolby** [comment]
Works for gccgo 7.3 and 8.1 on ppc64.

**Comment by GJRTimmer** [comment]
@tdolby Thanks.

**Pull request merged**
