### PR TITLE
*fix) add define HAVE_USLEEP

### PR DESCRIPTION
**Pull request by wuranbo**
It's what I used for the issue #148 
Based on this blog http://beets.radbox.org/blog/sqlite-nightmare.html, http://mail-index.netbsd.org/current-users/2012/06/01/msg020320.html.
It works fine to me now, but I am very NOT sure it is the code what solved the problem.

Just PR for more discuss.The #148 has obstruct me days.

### CODE REVIEW

**Comment by donlzx** [comment]
This works for my issue (database is locked). Thanks!

**Comment by mattn** [comment]
do NOT define in sqlite3-binding.c 
please add cgo CFLAGS.

**Comment by wuranbo** [comment]
@mattn got it. @donlzx attention buddy.

**Comment by ligustah** [comment]
+1

I ran into this error as well.

**Pull request closed without merging**
