### PR TITLE
Add functions to register update, commit, and rollback hooks.

### PR DESCRIPTION
**Pull request by brokensandals**
This would address #177

### CODE REVIEW

**Comment by siscia** [comment]
@mattn : It is really a pity that that this PR is not been considered much.

**Comment by mattn** [comment]
Seems good to me. Could you please rebase master?

**Comment by siscia** [comment]
@mattn , @brokensandals I may do it, but it will take me a while, I am a little busy and I don't know the basecode so well.

@brokensandals feel free to jump in whenever you want.

**Comment by brokensandals** [comment]
@mattn thanks for taking a look. I no longer have a use case for this functionality and won't be offended if you choose not to merge it, but I went ahead and rebased since it sounds like it may be useful to others.

**Comment by Jason-Abbott** [comment]
@mattn Any chance of reconsidering this for merge? I'd be happy to contribute with testing, rebasing, whatever, though it looks like the original PR was pretty complete.

I was planning to do some testing with these hooks before I discovered they aren't implemented here.

**Comment by mattn** [comment]
Sorry. I wonder why I closed this. Could you please rebase master?

**Comment by Jason-Abbott** [comment]
I don't have access to @brokensandals branch to rebase but I made my own fork that copies and credits his changes. I'll rebase and PR that.

**Comment by Jason-Abbott** [comment]
@mattn I made #434 since I don't have access to rebase the branch for this PR.

**Comment by mattn** [comment]
closed by https://github.com/mattn/go-sqlite3/pull/434

**Pull request closed without merging**
