### PR TITLE
add SystemErrno to Error

### LINKED ISSUE #678: Add low-level system error code to Error struct
Based my discussion with @rittneje in #618, we've realised that it would be really useful to add low-level system error code to [Error struct](https://godoc.org/github.com/mattn/go-sqlite3#Error).

> ## Low-level system error code
>
>     int sqlite3_system_errno(sqlite3*);
>
> Attempt to return the underlying operating system error code or error number that caused the most recent I/O error or failure to open a file. The return value is OS-dependent. For example, on unix systems, after `sqlite3_open_v2()` returns `SQLITE_CANTOPEN`, this interface could be called to get back the underlying "errno" that caused the problem, such as `ENOSPC`, `EAUTH`, `EISDIR`, and so forth.
>
> https://www.sqlite.org/c3ref/system_errno.html

If the maintainers are fine with it, I can give it a try as well. =)

### PR DESCRIPTION
**Pull request by rittneje**
fixes #678

### CODE REVIEW

**Comment by rittneje** [comment]
@mattn @GJRTimmer `sqlite3_system_errno` was added in SQLite 3.12.0. I guess whatever version you are using in the libsqlite3 tests is older than that. I don't see anywhere in your README that mentions a minimum required version of libsqlite3. How would you like me to proceed?

**Comment by rittneje** [comment]
@mattn @GJRTimmer I was able to leverage the C pre-processor to work around the version issue.

**Comment by GJRTimmer** [comment]
> @mattn @GJRTimmer `sqlite3_system_errno` was added in SQLite 3.12.0. I guess whatever version you are using in the libsqlite3 tests is older than that. I don't see anywhere in your README that mentions a minimum required version of libsqlite3. How would you like me to proceed?

The libsqlite3 test is using the library on the Travis CI system. Don't know if we can update to force a specific version.

**Comment by GJRTimmer** [comment]
@rittneje On first glance, this PR look great.

**Comment by mattn** [comment]
Sounds good to me.

**Comment by GJRTimmer** [comment]
@mattn What is the default we are using for merging "Create a Merge Request" of "Squash and merge"

**Comment by mattn** [comment]
I don't have strong opinion. Feel free to create rule if you want. :)

**Comment by rittneje** [comment]
@GJRTimmer @mattn Can this be merged?

**Comment by rittneje** [comment]
ping @mattn

**Comment by mattn** [comment]
Thanks

**Pull request merged**
