### PR TITLE
Add Additional Features / Options

### PR DESCRIPTION
**Pull request by GJRTimmer**
[New README Preview](https://github.com/GJRTimmer/go-sqlite3/tree/update/options)

# ADD
* SQLITE_ALLOW_URI_AUTHORITY
* SQLITE_ENABLE_API_ARMOR
* SQLITE_DEFAULT_FOREIGN_KEYS
* SQLITE_INTROSPECTION_PRAGMAS
* SQLITE_SECURE_DELETE
* SQLITE_ENABLE_STAT4
* SQLITE_DEFAULT_AUTOVACUUM

# Update
* README
  * [Feature Table](https://github.com/GJRTimmer/go-sqlite3/tree/update/options#features)
  * [TOC](https://github.com/GJRTimmer/go-sqlite3/tree/update/options#overview)
  * Renamed files of existing features to aggregate them based on filename.

### CODE REVIEW

**Comment by mattn** [comment]
Do you want to add some of them into .travis.yaml?

**Comment by mattn** [comment]
I'd like to say for everyone that see this PR, I will not promise that the options will stable in feature. I possibly may include some of them into default feature. :)

**Comment by mattn** [comment]
And I regret that these some tags should have sqlite3- prefix. If possible, I want to the tags which does not have the prefix of sqlite3- be deprecated.

**Comment by GJRTimmer** [comment]
I understand and agree. I will add them to `Travis CI`.

I understand that some options will be enabled by default in the future, but some should be left to the user, or we should follow SQLite itself. For example; foreign keys check is still not enabled by default by SQLite itself. So should we not follow the same convention ? Let me know

# Deprecation
To make sure I understand you completly, you want to deprecate the tag; ìcu` `json1` `fts5` and you want me to change them to `sqlite_icu` and keep the original `isu` for some time. At the moment you want  both tags to work. And in the future you will remove the old one.

I will make the changes you want.

**Comment by mattn** [comment]
Thanks. So I want to rename all of opt tags include . Could you please add `sqlite_` prefix for them?

fts5 => sqlite_fts5 fts5
icu => sqlite_icu icu
json1 => sqlite_json1 json1
see => sqlite_see see
trace => sqlite_trace trace
userauth => sqlite_userauth userauth
vtable => sqlite_vtable vtable

I'll keep older tag name for the time being to be possible to build with both tags. And I'll make the feature-tags which doesn't include sqlite_ prefix deprecated.

**Comment by mattn** [comment]
One more please, update .travis.yml with using new `sqlite_` prefix.

**Comment by GJRTimmer** [comment]
@mattn I've renamed everything to what you wanted.

# Updates
* Travis CI now uses new names
* Addition: Travis CI > for `sqlite_userauth` (Not present in this branch, will you make the build tag change in the branch where this tag is used ?)
* Addition: Travis CI < for `sqlite_see` (Not present in this branch, will you make the build tag change in the branch where this tag is used ?)
* json1 => `sqlite_json sqlite_json1 json1` (This is just for user conveniance)

**Comment by GJRTimmer** [comment]
Travis CI now fully updated, forget to add the additional jobs for the Windows Cross-Compile.
These have now been added.

**Comment by mattn** [comment]
Thanks. I'll merge this after CI succeeded.

**Comment by GJRTimmer** [comment]
You will update the `SEE` branch afterwards and the branch where the ùserauth` tag is used right ?

**Comment by mattn** [comment]
No, that was garbage. Thanks.

**Comment by GJRTimmer** [comment]
Then I suggest we leave the `sqlite_see` tag and `sqlite_userauth` tag in travis-ci.yml for the future.

**Comment by GJRTimmer** [comment]
@mattn on OSX module ICU fails: unicode/utypes.h is missing I do not own a Mac do you know which package we need to install ?

**Comment by mattn** [comment]
now travis stop?

**Comment by GJRTimmer** [comment]
Yeah stop Travis. I will make it shorter

**Comment by GJRTimmer** [comment]
@mattn Travis-CI Updated, currently running hope that you can merge this PR when its done.

**Comment by GJRTimmer** [comment]
@mattn Still trouble with compiling the `icu` module on OSX. Do you know how to do this, adding `brew install icu4c` had no effect.

**Comment by mattn** [comment]
@GJRTimmer Thanks your working on this. Sorry, I don't have OSX. So can not help you...

**Comment by GJRTimmer** [comment]
@mattn I'm now trying with Stackoverflow to fix this.

**Comment by GJRTimmer** [comment]
@mattn Think I succesfully fixed it, will merge my `fix/darwin-icu` branch into this one, then rebuild and we should have a complete succesfull build for ALL feature modules on several platforms 👍 

For the `icu` module I've added additional CFLAGS and LDFLAGS only for darwin, apparently you have to manually include it on OSX.

**Comment by GJRTimmer** [comment]
@mattn Please cancel #709 #710 Travis Builds for me

**Comment by GJRTimmer** [comment]
@mattn Build successful

**Comment by GJRTimmer** [comment]
@mattn Ready to merge 👍

**Comment by mattn** [comment]
Thanks. I'll check this on Windows later.

**Comment by mattn** [comment]
LGTM on Windows. Thank you.

**Pull request merged**
