### PR TITLE
Fix version in go.mod file

### LINKED ISSUE #812: Can't upgrade to version 2.0.5
I can't upgrade to version 2.0.5 on go 1.14:

```
$ go get -u github.com/mattn/go-sqlite3@v2.0.5
go: finding github.com/mattn/go-sqlite3 v2.0.5
go get github.com/mattn/go-sqlite3@v2.0.5: github.com/mattn/go-sqlite3@v2.0.5: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

I suspect this is because go-sqlite3 does not respect the [go module semantic versioning path](https://github.com/golang/go/wiki/Modules#faqs--semantic-import-versioning).
I'll try to send a fix.

 Related: https://github.com/golang/go/issues/35732

### PR DESCRIPTION
**Pull request by kolaente**
Fixes #812

### CODE REVIEW

**Comment by mattn** [comment]
You can upgrade with `go get -u github.com/mattn/go-sqlite3`.

See https://github.com/mattn/go-sqlite3/issues/755

**Comment by kolaente** [comment]
@mattn I tried that, it did not upgrade. I still have `	github.com/mattn/go-sqlite3 v2.0.3+incompatible` in my `go.mod` file.

**Comment by mattn** [comment]
How about this?

```
go get -u github.com/mattn/go-sqlite3@v2.0.5
```

**Comment by kolaente** [comment]
Gives me the error mentioned in #812:

```
$ go get -u github.com/mattn/go-sqlite3@v2.0.5
go: finding github.com/mattn/go-sqlite3 v2.0.5
go get github.com/mattn/go-sqlite3@v2.0.5: github.com/mattn/go-sqlite3@v2.0.5: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

**Comment by vtolstov** [comment]
you have only 3 ways 
- update go.mod to have /v2 and users must use /v2 to their import paths for never features
- drop go.mod stuff
- create v2 dir and copy files to it and commit

**Comment by mattn** [comment]
I tagged v1.14.0 for latest release. If you are using v2.0.3, please use v1.14.0 instead.

See https://github.com/mattn/go-sqlite3/issues/812#issuecomment-644147425

**Pull request closed without merging**
