### PR TITLE
Move RegisterAggregator implementation

### PR DESCRIPTION
**Pull request by kenshaw**
The SQLiteConn.RegisterAggregator implementation was defined in
sqlite3_trace.go file, which is guarded with a build constraint. This
change simply moves RegisterAggregator to the main sqlite3.go file,
and moves accompanying unit tests.

The rationale for this move is that it was not possible for downstream
using packages to use RegisterAggregator without also specifying (and
notifying the user) the 'trace' build tag.

### CODE REVIEW

**Comment by kenshaw** [comment]
It's worth noting that (philosophically) this should probably be used/tested in the same place as RegisterFunc. Also, worth mentioning is that the additional GOTAGS=trace environment in the travis-ci configuration is no longer necessary, as the *_trace_test.go only tested the RegisterAggregator func.

**Comment by kenshaw** [comment]
Just bumping this to determine if this will be merged or not. If there is anything that I need to change in this PR to get it included, please let me know. Thanks!

**Comment by mattn** [comment]
LGTM. I'll check more something for merge.

**Comment by mattn** [comment]
Thank you!

**Comment by kenshaw** [comment]
Thanks for the merge -- really appreciate all the work you do @mattn on this project and others. Cheers!

**Pull request merged**
