### PR TITLE
new go1.8 feature

### PR DESCRIPTION
**Pull request by mattn**
Closing https://github.com/mattn/go-sqlite3/issues/346

## On Conn
* [x] BeginContext(ctx) (tx,err) found in ConnBeginContext
* [x] PrepareContext(ctx, query) (stmt,err) found in ConnPrepareContext
* [x] ExecContext(ctx, query, []namedvalue) (res, err)  found in ExecerContext
* [x] Ping(ctx) err found in Pinger
* [x] QueryContext(ctx, query, []namedvalue) (rows, err) found in QueryerContext

## On "Stmt"
* [x] ExecContext(ctx, []namedvalue) (res, err) found in StmtExecContext
* [x] QueryContext(ctx, []namedvalue) (rows, err) found in StmtQueryContext

## On "Rows"
* [ ] HasNextResultSet() bool found in RowsNextResultSet
* [ ] NextResultSet() error found in RowsNextResultSet
* [x] ColumnTypeDatabaseTypeName(index int) (name string)
* [x] ColumnTypeLength(index int) (length int64, ok bool)
* [x] ColumnTypeNullable(index int) (nullable, ok bool)
* [x] ColumnTypePrecisionScale(index int) (precision, scale int64, ok bool)
* [x] ColumnTypeScanType(index int) reflect.Type

### CODE REVIEW

**Comment by mattn** [comment]
I decide NOT to support NextResultSet/HasNextResultSet because the go's multiple result is not same as sqlite's one.

**Comment by azavorotnii** [comment]
@mattn is there some workaround for NextResultSet usage? Currently, if I have multiple selects in same Query() it returns only last select rows.

**Comment by mattn** [comment]
When I looked at database / sql before, it seemed impossible to implement multiple-resultset for sqlite3 because the behavior of multiple-resultset of database/sql is different from the one expected. But now I looked it, I seems possible to implement. (Seems HasNextResultSet is gone, but not problem)

**Comment by mattn** [comment]
https://github.com/mattn/go-sqlite3/issues/497

**Pull request merged**
