### PR TITLE
Implement support for calling Go functions from SQLite

### LINKED ISSUE #226: Support for UDFs?
For me, one of the most interesting features of SQLite, is the ability to extend the behaviour of SQL queries by implementing simple or aggregate UDFs (user-defined functions).

They are critical to implement the REGEXP operator for instance, and, in my current scenario, a RANK() function that operates on data returned by the FTS matchinfo().

I don't think I've seen anything regarding this in the docs (in pure Go). Would it be even possible to do it without C?

### PR DESCRIPTION
**Pull request by danderson**
Fixes #226.

Supports scalar functions and aggregation functions.

I've benchmarked the call stack, and even with the reflection, the performance matches the QueryRow benchmark (18 microseconds per "SELECT custom_func(1,2)").

### CODE REVIEW

**Comment by mattn** [comment]
Oh, awesome. I'll look into it in later.

**Comment by danderson** [comment]
I also have ideas for improvements to this code (do more work in register, less work in the actual call, and support more data types), but the change was becoming quite big, so if you're okay with it, I'll send the improvements in separate changes/pull requests.

**Comment by danderson** [comment]
Ping?

**Comment by mattn** [comment]
I'll merge this after CI. :+1:

**Comment by mattn** [comment]
Could you handle error on CI?

**Comment by danderson** [comment]
Sorry, there was a typo in one of the tests. Fixed and repushed, CI passes now.

**Comment by mattn** [comment]
Coooooooooool! :+1:

**Comment by Dashed** [comment]
This is slick. :+1:

**Pull request merged**
