### PR TITLE
Fix building with "trace"

### PR DESCRIPTION
**Pull request by fancycode**
This should hopefully fix the remaining of #352.

### CODE REVIEW

**Comment by fancycode** [comment]
Please wait for Travis to finish before merging this to see if anything else needs to be changed.

**Comment by fancycode** [comment]
@mattn Building now works for all cases but `libsqlite3 trace`:
```
could not determine kind of name for C.SQLITE_DETERMINISTIC
could not determine kind of name for C.SQLITE_TRACE_CLOSE
could not determine kind of name for C.SQLITE_TRACE_PROFILE
could not determine kind of name for C.SQLITE_TRACE_ROW
could not determine kind of name for C.SQLITE_TRACE_STMT
could not determine kind of name for C.sqlite3_expanded_sql
could not determine kind of name for C.sqlite3_trace_v2
```

Is this supposed to work or should I remove it from the Travis build matrix? If it is unsupported it would be better to not build the tracing code if `libsqlite3` is defined (even it also `trace` is defined).

**Comment by mattn** [comment]
Thank you. But, I modified master branch already because it will need more fixes.

https://travis-ci.org/mattn/go-sqlite3/builds/174141111

**Comment by fancycode** [comment]
You should at least merge / cherry-pick this commit:
https://github.com/mattn/go-sqlite3/pull/354/commits/b11c6150cd1ddc8d69ff0e14cdd323c4b2f80c47

Otherwise the combination of `libsqlite3 trace` is not tested correctly in Travis (only sets `libsqlite3`). Also I rebased to your latest changes on master...

**Comment by mattn** [comment]
merged. thank you

**Comment by mattn** [comment]
libsqlite3 on travis is too old.

**Pull request closed without merging**
