### PR TITLE
Update amalgamation code

### PR DESCRIPTION
**Pull request by mattn**
Closes #989

### CODE REVIEW

**Comment by mattn** [comment]
Hmm, sqlite3 seems to change behavior of dropping vtable.

```
=== RUN   TestCreateModuleEponymousOnly
    sqlite3_opt_vtable_test.go:606: couldn't drop virtual table: table test may not be dropped
--- FAIL: TestCreateModuleEponymousOnly (0.00s)
```

**Comment by rittneje** [comment]
Yes, this is no longer supported. https://sqlite.org/src/info/889dea52de874cd3

**Comment by mattn** [comment]
@rittneje Thank you

**Comment by dsymonds** [comment]
Ready to submit?

**Pull request merged**
