### PR TITLE
Fix #213

### LINKED ISSUE #213: Is there any way to use the driver with SQLITE_ENABLE_UPDATE_DELETE_LIMIT flag?
This flag is useful when one is executing DELETE query with LIMIT clause: `DELETE FROM "sometable"  WHERE (name = 'foo') LIMIT 5`.
By default the driver returns an error: `near "LIMIT": syntax error`.

Is there any way to enable it for the driver? There is one possible problem: documentation says that this flag cannot be used with "amalgamation" source of sqlite3 driver: https://www.sqlite.org/compile.html

### PR DESCRIPTION
**Pull request by GJRTimmer**
ADD: SQLITE_ENABLE_UPDATE_DELETE_LIMIT

Fixes: #213

### CODE REVIEW

**Comment by mattn** [comment]
Thank you

**Comment by EmpireJones** [comment]
I'm trying to interpret this comment:
https://github.com/mattn/go-sqlite3/pull/215#issuecomment-391655257
> note that not mean that this enabling delete limit also when using libsqlite3 on system always.

Am I understanding correctly that this feature is **only** available with usage of a separate build of libsqlite3, and **not** the "linux" tag build, as that one uses the 'amalgamation'?

**Comment by mholt** [comment]
How does one use this change? I get `near "LIMIT": syntax error` on the DELETE statement used in the test case.

**Comment by rittneje** [comment]
https://www.sqlite.org/compile.html#enable_update_delete_limit

"If this option is defined, then it must also be defined when using the Lemon parser generator tool to generate a parse.c file. Because of this, this option may only be used when the library is built from source, not from the amalgamation or from the collection of pre-packaged C files provided for non-Unix like platforms on the website."

Just adding the compile-time option is not sufficient. You would need a custom amalgamation.

**Comment by mholt** [comment]
I see, thank you for the tip!

**Pull request merged**
