### PR TITLE
fix/test/coverage

### PR DESCRIPTION
**Pull request by GJRTimmer**
PR to increase coverage

***NOT READY TO MERGE***

### CODE REVIEW

**Comment by mattn** [comment]
Thank you

**Comment by mattn** [comment]
Ooops. Sorry. This was not ready to merge...

**Comment by mattn** [comment]
@GJRTimmer Do we have better to revert?

**Comment by GJRTimmer** [comment]
@mattn not needed to revert, this first coverage update was ready, now I simply will create a new branch to increase coverage.

**Pull request merged**
